version: '3.8'
services:
  internetbanking:
    image: chhatrapal7/image-2:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/image-2
  mobilebanking:
    image: chhatrapal7/ib-images:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/ib-images
  insurance:
    image: chhatrapal7/chhatrapal:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/chhatrapal
