version: '3.8'
services:
  internetbanking:
    image: chhatrapal7/ib-image:latest
    ports:
      - "51:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/ib-image
  internetbanking2:
    image: chhatrapal7/ib-image:latest
    ports:
      - "52:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/ib-image
